CvBuddy/Controllers/MessageController.cs
using bla.Model;
using bla.Model.CvInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Reflection;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using bla.DAL;

namespace bla.Controllers
{
    public class MessageController : BaseController
    {

        public MessageController(UserManager<User> u, CVBuddyContext c, SignInManager<User> sm) : base(u, c, sm)
        {
        }

        [HttpGet]
        public IActionResult SendMsg(string userId)
        {
            MessageVM msg = new();
            msg.RecieverId = userId;


            return View(msg);
        }
        [HttpPost]
        public async Task<IActionResult> SendMsg(MessageVM msgVM)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(msgVM);

                Message msg = new Message
                {
                    Mid = msgVM.Mid,
                    Sender = msgVM.Sender,
                    MessageString = msgVM.MessageString,
                    SendDate = msgVM.SendDate,
                    IsRead = msgVM.IsRead,
                    RecieverId = msgVM.RecieverId
                };

                await _context.AddAsync(msg);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            catch (DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Could not send message, internal error while trying to save your message to the database."});
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});
            }

            
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Messages()
        {

            try
            {
                var userId = _userManager.GetUserId(User);

                List<MessageVM> mVMList = await _context.Messages
                    .Where(m => m.RecieverId == userId)
                    .OrderByDescending(m => m.SendDate)
                    .Select(m => new MessageVM
                    {
                        Mid = m.Mid,
                        Sender = m.Sender,
                        MessageString = m.MessageString,
                        SendDate = m.SendDate,
                        IsRead = m.IsRead,
                        RecieverId = m.RecieverId
                    })
                    .ToListAsync();

                return View(mVMList);
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Internal error retrieveing your messages from the database."});
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> UpdateIsRead(Message message, int mid)
        {
            try
            {
                var oldState = await _context.Messages.FindAsync(mid);

                oldState!.IsRead = message.IsRead;
                await _context.SaveChangesAsync();
                return RedirectToAction("Messages");
            }
            catch (DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Could not save changes to read status, internal error while trying to save your changes." });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> ReadMsg(int mid)
        {
            
            try
            {
                var msg = await _context.Messages
                    .FindAsync(mid);

                if (msg == null)
                    return NotFound("Message could not be found.");

                MessageVM mVM = new MessageVM
                {
                    Mid = msg.Mid,
                    Sender = msg.Sender,
                    MessageString = msg.MessageString,
                    SendDate = msg.SendDate,
                    IsRead = msg.IsRead,
                    RecieverId = msg.RecieverId
                };
                return View(mVM);
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Error finding your message." });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
        }
        
        [HttpGet]
        public async Task<IActionResult> DeleteMessageConfirm(int mid)
        {
            
            try
            {
                var message = await _context.Messages.FirstOrDefaultAsync(m => m.Mid == mid);
                if (message == null)
                    throw new NullReferenceException("This message could not be found.");
                MessageVM mVM = new MessageVM
                {
                    Mid = message.Mid,
                    Sender = message.Sender,
                    MessageString = message.MessageString,
                    SendDate = message.SendDate,
                    IsRead = message.IsRead,
                    RecieverId = message.RecieverId
                };

                return View(mVM);
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});

            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an error deleting the message" });

            }

            
        }

        [HttpGet]
        public async Task<IActionResult> DeleteMessage(MessageVM mVM)
        {            
            try
            {
                var message = await _context.Messages.FirstOrDefaultAsync(m => m.Mid == mVM.Mid);

                if (message == null)
                    throw new NullReferenceException("The message you want to delete could not be found.");
                
                //Radera
                _context.Messages.Remove(message);

                //Savechangesasync
                await _context.SaveChangesAsync();
                return RedirectToAction("Messages");
            }
            catch(DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Failed to delete the message, due to an issue saving your changes."});
            }
            catch(NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
            catch(Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an error deleting the message" });
            }
            
        }

    }
}

CvBuddy/Controllers/OptionsController.cs
using bla.Model;
using bla.Model.CvInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using bla.DAL;

namespace bla.Controllers
{
    public class OptionsController : HomeController
    {
        public OptionsController(UserManager<User> u, CVBuddyContext c, SignInManager<User> sm) : base(u, c, sm)
        {
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> GetOptions()
        {
            try
            {
                OptionsViewModel optViewModel = new();

                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                    throw new NullReferenceException("User could not be retrieved.");

                ViewBag.IsSetToDeactivated = user.IsDeactivated;
                ViewBag.HasSetProfilePrivate = user.HasPrivateProfile;
                optViewModel.IsDeactivated = ViewBag.IsSetToDeactivated;
                optViewModel.HasPrivateProfile = ViewBag.HasSetProfilePrivate;

                return View();
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});
            }
        }

        
        [HttpPost]
        public async Task<IActionResult> GetOptions(OptionsViewModel optModel)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                
                if (user == null)
                    throw new NullReferenceException("User could not be retrieved.");

                user.IsDeactivated = optModel.IsDeactivated;
                user.HasPrivateProfile = optModel.HasPrivateProfile;

                await _userManager.UpdateAsync(user);

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            catch (DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an error saving the changes to the database."});
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
            
        }
    }
}

CvBuddy/Controllers/ProfileController.cs
using bla.Model;
using bla.Model.CvInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using bla.DAL;

namespace bla.Controllers
{
    public class ProfileController : BaseController
    {
        public ProfileController(UserManager<User> u, CVBuddyContext c, SignInManager<User> sm) : base(u, c, sm)
        {
        }

        [HttpGet]
        public async Task<IActionResult> ReadProfile(string userId)//Detta userId tillhör user cv som man kollar på, kan bara se denna knapp som ej inloggad där andra users har ett cv, 
        {
            try
            {
                var user = await _context.Users
                .Include(u => u.OneAddress)
                .Include(u => u.OneCv)
                .ThenInclude(cv => cv.Experiences)
                .Include(u => u.OneCv)
                .ThenInclude(cv => cv.Education)
                .Include(u => u.OneCv)
                .ThenInclude(cv => cv.Skills)
                .Include(u => u.OneCv)
                .ThenInclude(cv => cv.Certificates)
                .Include(u => u.OneCv)
                .ThenInclude(cv => cv.Interests)
                .Include(u => u.OneCv)
                .ThenInclude(cv => cv.PersonalCharacteristics)
                .FirstOrDefaultAsync(u => u.Id.Equals(userId));



                if (user?.OneCv == null)//samma knapp används för att visa "My profile", om man inte har ett eget Cv så, måste man skapa ett Cv innan man kan se sin profil. Därför krävs bara en bild för att skapa ett Cv
                    return RedirectToAction("BuildCv", "CvInformation");


                ViewBag.HasOneAdress = user.OneAddress != null;
                ViewBag.HasOneCv = user?.OneCv != null; //HasOneCv för att om vi planerar på att man
                                                       //ska kunna komma till Profil sidan inte bara från en persons cv
                                                       //så är det inte garanterat att de har cv


                if (ViewBag.HasOneCv)//Om användaren vars profilknapp man klickar på har ett cv, så visas en "Cv" rubrik i view, det cvt måste ha en av respektive delar för att den ska visas tillsammans med den delens rubrik och content
                {
                    ViewBag.HasExperience = user.OneCv!.Experiences.Count() > 0;
                    ViewBag.HasHighSchool = user.OneCv!.Education?.HighSchool != null;
                    ViewBag.HasUniveristy = user.OneCv!.Education?.Univeristy != null;
                    ViewBag.HasSkills = user.OneCv!.Skills.Count() > 0;
                    ViewBag.HasCertificates = user.OneCv!.Certificates.Count() > 0;
                    ViewBag.HasInterests = user.OneCv!.Interests.Count() > 0;
                    ViewBag.HasPersonalCharacteristics = user.OneCv!.PersonalCharacteristics.Count() > 0;
                    //Om använderen bara har en bild för sitt cv så syns en ensam rubrik("Cv" rubriken från ovanstående kommenta), ta bort den med detta
                    ViewBag.HasCvWithOnlyImage = false;
                    if (ViewBag.HasExperience ||
                        ViewBag.HasHighSchool ||
                        ViewBag.HasUniveristy ||
                        ViewBag.HasSkills ||
                        ViewBag.HasCertificates ||
                        ViewBag.HasInterests ||
                        ViewBag.HasPersonalCharacteristics)
                    {
                        ViewBag.HasCvWithOnlyImage = true;
                    }

                }

                var projects = await _context.Projects
                    .Include(p => p.ProjectUsers)
                    .ThenInclude(pu => pu.User)
                    .Where(u => u.ProjectUsers.Any(pu => pu.UserId == userId))
                    .ToListAsync();

                var isAuthenticated = User.Identity!.IsAuthenticated;

                var projectVMs = new List<ProjectVM>();


                foreach (var project in projects)
                {
                    var owner = project.ProjectUsers
                        .FirstOrDefault(pu => pu.IsOwner);

                    if (owner == null)
                        continue;

                    if (owner.User.IsDeactivated)
                        continue;

                    if (!isAuthenticated && owner.User.HasPrivateProfile)
                        continue;

                    var usersInProject = project.ProjectUsers
                        .Select(pu => pu.User).ToList();

                    var activeUsers = usersInProject.Where(u => !u.IsDeactivated).ToList();

                    var relation = project.ProjectUsers.FirstOrDefault(pu => pu.UserId == userId);

                    projectVMs.Add(new ProjectVM
                    {
                        Project = project,
                        Owner = owner,
                        Relation = relation,
                        IsUserInProject = true,
                        ActiveUsers = isAuthenticated ? activeUsers : activeUsers.Where(u => !u.HasPrivateProfile).ToList()
                    });
                }

                List<Project> projList = await _context.ProjectUsers
                    .Where(pu => pu.UserId == userId)
                    .Join(
                    _context.Projects,
                    pu => pu.ProjId,
                    p => p.Pid,
                    (pu, p) => p)
                    .ToListAsync();

                ViewBag.HasJoinedProjects = projList.Count() > 0;

                ViewBag.IsMyProfile = false;
                if (User.Identity!.IsAuthenticated)
                {
                    var loggedInUserId = _userManager.GetUserId(User);
                    ViewBag.IsMyProfile = loggedInUserId == userId;

                }

                ProfileViewModel profViewModel = new();

                profViewModel.ViewUser = user;
                profViewModel.Cv = user.OneCv;
                profViewModel.Projects = projectVMs;


                return View(profViewModel);
            }
            catch(Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});
            }
            
        }
    }
}

CvBuddy/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> _userManager

@{
    var currentUserId = _userManager.GetUserId(User);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CVBuddy</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CVBuddy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm  navbar-light bg-white border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CVBuddy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse ">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                    @if (!User.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login"><i class="fa-solid fa-door-open"></i>Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register"><i class="fa-solid fa-pen"></i>Register</a>
                            </li>
                            <a class="nav-link locked-out-for-text" asp-controller="Message" asp-action="Messages">
                                <i class="fa-solid fa-envelope"></i>
                                Messages <b id="notification"></b><i class="fa-sharp-duotone fa-solid fa-lock"></i>
                            </a>
                        }
                        else
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Message" asp-action="Messages">
                                    <i class="fa-solid fa-envelope"></i>
                                    Messages <b id="notification">@(ViewBag.NotReadCount ?? "0")</b>
                                </a>
                                
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid flex-grow-1">
        <div class="row h-100 flex-nowrap align-items-stretch">
            <aside class="col-md-3 col-lg-2 bg-light p-3  d-flex flex-column">
                <h6 class="text-uppercase">Meny</h6>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link" asp-controller="Profile" asp-action="ReadProfile" asp-route-userId="@currentUserId"><i class="fa-solid fa-shapes"></i>   My profile</a>
                        }
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="User" asp-action="GetUser"><i class="fa-solid fa-user"></i>   My Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="CvInformation" asp-action="ReadCv"><i class="fa-solid fa-file"></i>   My CV</a>@* Länk till cv, om finns ingen cv, utskrift, och knapp skapa cv *@
                    </li>
                    
                    <li class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link" asp-controller="Project" asp-action="GetProject"><i class="fa-solid fa-diagram-project"></i>   My Projects</a> @* lista med projekt,vid varje projekt knapp update/delete *@
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Project" asp-action="GetProject"><i class="fa-solid fa-diagram-project"></i>   Projects</a> @* lista med projekt,vid varje projekt knapp update/delete *@

                        }
                    </li>
                </ul>
                <ul class="nav flex-column mt-auto">
                    <li class="nav-item">

                        <a class="nav-link" asp-controller="Options" asp-action="GetOptions"><i class="fa-solid fa-gear"></i>   Options</a>
                    </li>
                </ul>
            </aside>
            <main role="main" class="col-md-9 col-lg-10 p-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top text-muted">
        <div class="container-fluid text-center py-3">
            &copy; 2025 - CVBuddy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>