CvBuddy/Controllers/CvInformationController.cs
using Castle.Components.DictionaryAdapter.Xml;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.Intrinsics.Arm;
using System.Security.Cryptography;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using bla.Model;
using bla.Model.CvInfo;
using bla.DAL;


// ---->Längst nere finns förklaringar till det helper metoder som används här och anledningen till varför dem behöves. <----


namespace bla.Controllers
{
    public class CvInformationController : BaseController
    {
        public CvInformationController(UserManager<User> u, CVBuddyContext c, SignInManager<User> sm) : base(u, c, sm) { }

        //---------------------BuildCv------------------------------------------BuildCv---------------------

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> BuildCv()//TILL BUILD CV-SIDAN ----->>>>
        {
            return View(new CvVM());
        }

        [HttpPost]
        public async Task<IActionResult> BuildCv(CvVM cvVM)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(cvVM);
                Cv cv = new Cv
                {
                    ImageFilePath = cvVM.ImageFile!.Name,
                    UserId = _userManager.GetUserId(User)
                };

                cv.Education = new();

                var uploadeFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "CvImages");
                Directory.CreateDirectory(uploadeFolder);

                var ext = Path.GetExtension(cvVM.ImageFile.FileName);

                var fileName = Guid.NewGuid().ToString() + ext;

                var filePath = Path.Combine(uploadeFolder, fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await cvVM.ImageFile.CopyToAsync(stream);
                }
                cv.ImageFilePath = "/CvImages/" + fileName;

                await _context.Cvs.AddAsync(cv);
                await _context.SaveChangesAsync();

                return RedirectToAction("UpdateCv");
            }
            catch (DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Could not create Cv, encountered an error while saving to database" });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an unexpected error while trying to create your Cv." });
            }
        }

        //---------------------ReadCv------------------------------------------ReadCv---------------------


        [HttpGet]
        public async Task<IActionResult> ReadCv(int? Cid) 
        {
            Cv? cv;
            try
            {
                if (Cid.HasValue) 
                {
                    //Man hamnar här om man inte äger cv:t själv

                    cv = await _context.Cvs
                    .Include(cv => cv.Education)
                    .Include(cv => cv.Experiences)
                    .Include(cv => cv.Skills)
                    .Include(cv => cv.Certificates)
                    .Include(cv => cv.PersonalCharacteristics)
                    .Include(cv => cv.Interests)
                    .Include(cv => cv.OneUser)
                    .ThenInclude(oneUser => oneUser!.ProjectUsers)
                    .FirstOrDefaultAsync(cv => cv.Cid == Cid);

                    if (cv == null)
                        throw new NullReferenceException("Could not find Cv");

                    cv.UsersProjects = await GetProjectsUserHasParticipatedIn(cv.UserId!);

                    var usersCv = await GetLoggedInUsersCvAsync();
                    ViewBag.NotLoggedInUsersCv = cv?.UserId != usersCv?.UserId;
                    if (ViewBag.NotLoggedInUsersCv)
                    {
                        await _context.Database.ExecuteSqlRawAsync("UPDATE Cvs SET ReadCount = ReadCount + 1 WHERE Cid = " + Cid); //Inkrementera ReadCount varje gång See Cv klickas 
                    }
                }
                else//I else hämtas den inloggade användarens Cv, för "My Cv" och där användaren klickar see cv på sitt eget cv
                {
                    if (!User.Identity!.IsAuthenticated)
                    {
                        return RedirectToAction("Login", "Account");//För att både inloggade och utloggade ska använda samma action metod för att see ett cv
                    }
                    else
                    {
                        cv = await GetLoggedInUsersCvAsync();

                        if (cv == null)
                                return RedirectToAction("BuildCv");
                    }

                }

                ViewBag.HasSetPrivateProfile = cv?.OneUser!.HasPrivateProfile;

                //För headlines om det finns något att visa under headlinen till view
                ViewBag.Headline = "Cv";

                ViewBag.CvOwnerFullName = " - " + cv?.OneUser.GetFullName();

                //Experiences
                if (cv?.Experiences.Count > 0)
                {
                    ViewBag.HeadlineExperiences = "Experiences";
                }

                //Education
                bool hasEducation = false;
                var cvEdu = cv?.Education;

                if (cvEdu?.HighSchool != null || cvEdu?.HSProgram != null || cvEdu?.HSDate != null)
                    hasEducation = true;

                if (cvEdu?.Univeristy != null || cvEdu?.UniProgram != null || cvEdu?.UniDate != null)
                    hasEducation = true;

                if (hasEducation)
                    ViewBag.HeadlineEducation = "Education";

                //Skills
                if (cv?.Skills.Count > 0)
                {
                    ViewBag.HeadlineSkill = "Skills";
                }

                //Certificates
                if (cv?.Certificates.Count > 0)
                {
                    ViewBag.HeadlineCertificates = "Certificates";
                    ViewBag.HeadlineCertificatesSmall = "My Certificates";
                }

                //Personal Characteristics
                if (cv?.PersonalCharacteristics.Count > 0)
                {
                    ViewBag.HeadlinePersonalCharacteristics = "Personal Characteristics";
                    ViewBag.HeadlinePersonalCharacteristicsSmall = "My personal characteristics";

                }

                //Interests
                if (cv?.Interests.Count > 0)
                {
                    ViewBag.HeadlineInterest = "Interests";
                    ViewBag.HeadlineInterestSmall = "These are my interests";
                }

                if (cv?.UsersProjects.Count > 0)
                {
                    ViewBag.HeadlineProjects = "Projects";
                    ViewBag.HeadlineProjectsSmall = "I have participated in these projects";
                }

                return View(cv);
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
            catch (OperationCanceledException)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "A database operation was canceled while incrementing this Cvs read counter" });
            }
            catch (Exception)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an error retrieving Cv and additional information. " });
            }


        }

        //---------------------UpdateCv------------------------------------------UpdateCv---------------------

        [HttpGet]
        public async Task<IActionResult> UpdateCv()
        {
            try
            {
                var cv = await GetLoggedInUsersCvAsync();

                if (cv == null)
                    throw new NullReferenceException("Users Cv could not be found.");

                CvVM cvVM = new CvVM
                {
                    Cid = cv.Cid,
                    Skills = cv.Skills,
                    Education = cv.Education,
                    Experiences = cv.Experiences,
                    Certificates = cv.Certificates,
                    PersonalCharacteristics = cv.PersonalCharacteristics,
                    PublishDate = cv.PublishDate,
                    Interests = cv.Interests,
                    ImageFilePath = cv.ImageFilePath,
                    ReadCount = cv.ReadCount,
                    UserId = cv.UserId
                };

                return View(cvVM);
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an unexpected error while getting your cv from the database." });
            }
        }

        //---------------------Image---------------------Image---------------------Image---------------------HÄÄÄÄR !!!!!!!!!!!!!!!!!!!!!!!

        [HttpGet]
        public async Task<IActionResult> UpdateImage()
        {
            var cvVM = await UsersCvToCvVM();
            return View(cvVM);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateImage(CvVM cvVM)
        {
            try
            {
                var cv = await GetLoggedInUsersCvAsync();
                if (cv == null)
                    throw new NullReferenceException("Users Cv could not be found.");

                cvVM.ImageFilePath = cv.ImageFilePath;

                if (!ModelState.IsValid)
                {

CvBuddy/Controllers/MessageController.cs
using bla.Model;
using bla.Model.CvInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Reflection;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using bla.DAL;

namespace bla.Controllers
{
    public class MessageController : BaseController
    {

        public MessageController(UserManager<User> u, CVBuddyContext c, SignInManager<User> sm) : base(u, c, sm)
        {
        }

        [HttpGet]
        public IActionResult SendMsg(string userId)
        {
            MessageVM msg = new();
            msg.RecieverId = userId;


            return View(msg);
        }
        [HttpPost]
        public async Task<IActionResult> SendMsg(MessageVM msgVM)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(msgVM);

                Message msg = new Message
                {
                    Mid = msgVM.Mid,
                    Sender = msgVM.Sender,
                    MessageString = msgVM.MessageString,
                    SendDate = msgVM.SendDate,
                    IsRead = msgVM.IsRead,
                    RecieverId = msgVM.RecieverId
                };

                await _context.AddAsync(msg);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            catch (DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Could not send message, internal error while trying to save your message to the database."});
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});
            }

            
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Messages()
        {

            try
            {
                var userId = _userManager.GetUserId(User);

                List<MessageVM> mVMList = await _context.Messages
                    .Where(m => m.RecieverId == userId)
                    .OrderByDescending(m => m.SendDate)
                    .Select(m => new MessageVM
                    {
                        Mid = m.Mid,
                        Sender = m.Sender,
                        MessageString = m.MessageString,
                        SendDate = m.SendDate,
                        IsRead = m.IsRead,
                        RecieverId = m.RecieverId
                    })
                    .ToListAsync();

                return View(mVMList);
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Internal error retrieveing your messages from the database."});
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> UpdateIsRead(Message message, int mid)
        {
            try
            {
                var oldState = await _context.Messages.FindAsync(mid);

                oldState!.IsRead = message.IsRead;
                await _context.SaveChangesAsync();
                return RedirectToAction("Messages");
            }
            catch (DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Could not save changes to read status, internal error while trying to save your changes." });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> ReadMsg(int mid)
        {
            
            try
            {
                var msg = await _context.Messages
                    .FindAsync(mid);

                if (msg == null)
                    return NotFound("Message could not be found.");

                MessageVM mVM = new MessageVM
                {
                    Mid = msg.Mid,
                    Sender = msg.Sender,
                    MessageString = msg.MessageString,
                    SendDate = msg.SendDate,
                    IsRead = msg.IsRead,
                    RecieverId = msg.RecieverId
                };
                return View(mVM);
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Error finding your message." });
            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
        }
        
        [HttpGet]
        public async Task<IActionResult> DeleteMessageConfirm(int mid)
        {
            
            try
            {
                var message = await _context.Messages.FirstOrDefaultAsync(m => m.Mid == mid);
                if (message == null)
                    throw new NullReferenceException("This message could not be found.");
                MessageVM mVM = new MessageVM
                {
                    Mid = message.Mid,
                    Sender = message.Sender,
                    MessageString = message.MessageString,
                    SendDate = message.SendDate,
                    IsRead = message.IsRead,
                    RecieverId = message.RecieverId
                };

                return View(mVM);
            }
            catch (NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message});

            }
            catch (Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an error deleting the message" });

            }

            
        }

        [HttpGet]
        public async Task<IActionResult> DeleteMessage(MessageVM mVM)
        {            
            try
            {
                var message = await _context.Messages.FirstOrDefaultAsync(m => m.Mid == mVM.Mid);

                if (message == null)
                    throw new NullReferenceException("The message you want to delete could not be found.");
                
                //Radera
                _context.Messages.Remove(message);

                //Savechangesasync
                await _context.SaveChangesAsync();
                return RedirectToAction("Messages");
            }
            catch(DbUpdateException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Failed to delete the message, due to an issue saving your changes."});
            }
            catch(NullReferenceException e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = e.Message });
            }
            catch(Exception e)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "There was an error deleting the message" });
            }
            
        }

    }
}

CvBuddy/Views/CvInformation/AddCertificate.cshtml
@model bla.Model.CvInfo.CertificateVM

<form asp-action="AddCertificate" method="post">
    <div class="d-flex justify-content-center align-content-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h3 class="text-center mb-4">Certificate</h3>
            
            <div class="mb-3">
                <label asp-for="@Model.CertName" class="form-label"></label>
                <input type="text" asp-for="@Model.CertName" class="form-control" />
                <span asp-validation-for="CertName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Add</button>
        </div>
    </div>
</form>

CvBuddy/Views/CvInformation/AddEducation.cshtml
@model bla.Model.CvInfo.EducationVM

<form asp-action="AddEducation" method="post">
    <div class="d-flex justify-content-center align-content-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h3 class="text-center mb-4">Education</h3>

            <div class="mb-3">
                <label asp-for="@Model.HighSchool" class="form-label"></label>
                <input type="text" asp-for="@Model.HighSchool" class="form-control" />
                <span asp-validation-for="HighSchool" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HSProgram" class="form-label"></label>
                <input type="text" asp-for="@Model.HSProgram" class="form-control" />
                <span asp-validation-for="HighSchool" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HSDate" class="form-label"></label>
                <input type="date" asp-for="@Model.HSDate" class="form-control" />
                <span asp-validation-for="HSDate" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Univeristy" class="form-label"></label>
                <input type="text" asp-for="@Model.Univeristy" class="form-control" />
                <span asp-validation-for="Univeristy" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.UniProgram" class="form-label"></label>
                <input type="text" asp-for="@Model.UniProgram" min="1900-01-01" max="2049-12-31" class="form-control" />
                <span asp-validation-for="UniProgram" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.UniDate" class="form-label"></label>
                <input type="date" asp-for="@Model.UniDate" min="1900-01-01" max="2049-12-31" class="form-control" />
                <span asp-validation-for="UniDate" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Add</button>
        </div>
    </div>
</form>

CvBuddy/Views/CvInformation/AddExperience.cshtml
@model bla.Model.CvInfo.ExperienceVM

<form asp-action="AddExperience" method="post">
    <div class="d-flex justify-content-center align-content-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h3 class="text-center mb-4">Experience</h3>

            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label"></label>
                <input type="text" asp-for="@Model.Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label"></label>
                <input type="text" asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Company" class="form-label"></label>
                <input type="text" asp-for="@Model.Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.StartDate" class="form-label"></label>
                <input type="date" asp-for="@Model.StartDate" min="1900-01-01" max="2049-12-31" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.EndDate" class="form-label"></label>
                <input type="date" asp-for="@Model.EndDate" min="1900-01-01" max="2049-12-31" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary w-100">Add</button>
        </div>
    </div>
</form>

CvBuddy/Views/CvInformation/AddInterest.cshtml
@model bla.Model.CvInfo.InterestVM

<form asp-action="AddInterest" method="post">
    <div class="d-flex justify-content-center align-content-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h3 class="text-center mb-4">Interest</h3>

            <div class="mb-3">
                <label asp-for="@Model.InterestName" class="form-label"></label>
                <input type="text" asp-for="@Model.InterestName" class="form-control" />
                <span asp-validation-for="InterestName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Add</button>
        </div>
    </div>
</form>

CvBuddy/Views/CvInformation/AddPersonalCharacteristic.cshtml
@model bla.Model.CvInfo.PersonalCharacteristicVM
<form asp-action="AddPersonalCharacteristic" method="post">
    <div class="d-flex justify-content-center align-content-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h3 class="text-center mb-4">Personal Characteristic</h3>

            <div class="mb-3">
                <label asp-for="@Model.CharacteristicName" class="form-label"></label>
                <input type="text" asp-for="@Model.CharacteristicName" class="form-control" />
                <span asp-validation-for="CharacteristicName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Add</button>
        </div>
    </div>
</form>

CvBuddy/Views/CvInformation/AddSkill.cshtml
@model bla.Model.CvInfo.SkillVM

@if (!ViewData.ModelState.IsValid)
{
    <h4 class="text-danger">You need to make some changes:</h4>
    <ul class="text-danger">
        @foreach (var err in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <li>
                @err.ErrorMessage
            </li>
        }
    </ul>
}


<form asp-action="AddSkill" method="post">
    <div class="d-flex justify-content-center align-content-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h3 class="text-center mb-4">Skill</h3>

            <div class="mb-3">
                <label asp-for="@Model.ASkill" class="form-label"></label>
                <input type="text" asp-for="@Model.ASkill" class="form-control" />
                <span asp-validation-for="ASkill" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label"></label>
                <input type="text" asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Date" class="form-label"></label>
                <input type="date" asp-for="@Model.Date" min="1900-01-01" max="2049-12-31" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Add</button>
        </div>
    </div>
</form>

CvBuddy/Views/CvInformation/ReadCv.cshtml
@model bla.Model.CvInfo.Cv



@* Styla snyggt  *@
<div class="d-flex flex-row justify-content-center gap-4">
    @if (ViewBag.NotLoggedInUsersCv != true) 
    {
        <a asp-controller="CvInformation" asp-action="UpdateCv" class="btn btn-primary"><i class="fa-solid fa-pencil"></i> Update cv</a>

        <a asp-controller="CvInformation" asp-action="DeleteCv" asp-route-Cid="@Model.Cid" class="btn btn-danger">DELETE</a>
    }
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary"><i class="fa-solid fa-house"></i> Home</a>
    
</div>

<div class="d-flex justify-content-center align-content-center min-vh-90">
    <div class="col-md-6 col-lg-10">
        <h1 class="mb-4">@ViewBag.Headline@ViewBag.CvOwnerFullName  - <i class="fa-regular fa-eye"></i> @Model.ReadCount</h1>

        <div class="mb-4 shadow read-banner">

            <div class="Cv-image">
                <img src="@Model.ImageFilePath" />
            </div>

            <div class="ml-2 contact-info-read-banner">
                <h3>Contact</h3>
                <p>@("Email:  " + Model.OneUser?.Email ?? "")</p>
                <p>@("Phone number:  " + Model.OneUser?.PhoneNumber ?? "")</p>
            </div>

            <div class="d-flex flex-column gap-2 justify-content-center interactions-read-banner">
                @if (ViewBag.HasSetPrivateProfile != true || User.Identity!.IsAuthenticated)
                {
                    <a asp-controller="Profile" asp-action="ReadProfile" asp-route-userId="@Model.OneUser!.Id" class="btn btn-primary btn-sm">
                        <i class="fa-regular fa-address-card"></i>
                        @if (ViewBag.NotLoggedInUsersCv != true)
                        {
                            <span>My</span>
                        }
                        Profile
                    </a>
                }
                @if (ViewBag.NotLoggedInUsersCv == true)
                {
                    <a asp-controller="Message" asp-action="SendMsg" asp-route-userId="@Model.OneUser!.Id" class="btn btn-outline-light btn-sm"><i class="fa-regular fa-message"></i>Send Message</a>
                }
            </div>
        </div>
        <div class="mb-4">
            <h2>@ViewBag.HeadlineExperiences</h2>

            @foreach (var experience in Model.Experiences)
            {
                <div class="mb-2 content-item">
                    <p class="mb-0">Title: @experience.Title</p>
                    <p class="mb-0">Company: @experience.Company</p>
                    <p class="mb-0">Description: @experience.Description</p>
                    <p class="mb-0">@experience.StartDate.ToShortDateString() <b>-</b> @(experience.EndDate?.ToShortDateString() ?? "Ongoing")</p>
                </div>
            }
        </div>

        <div class="mb-4">
            <h2>@ViewBag.HeadlineEducation</h2>
            @if (Model.Education.HighSchool != null)
            {
                <div class="mb-2 content-item">
                    <h5>HighSchool</h5>
                    <p class="mb-0">High School: @(Model.Education.HighSchool ?? "")</p>
                    <p class="mb-0">Program: @(Model.Education.HSProgram ?? "")</p>
                    <p class="mb-0">Date: @(Model.Education.HSDate ?? "Ongoing")</p>
                </div>
            }
            @if (Model.Education.Univeristy != null)
            {
                <div class="mb-2 content-item">
                    <h5>University</h5>
                    <p class="mb-0">University: @(Model.Education.Univeristy ?? "")</p>
                    <p class="mb-0">Program: @(Model.Education.UniProgram ?? "")</p>
                    <p class="mb-0">Date: @(Model.Education.UniDate ?? "Ongoing")</p>
                </div>
            }

        </div>
        <div class="mb-4">
            <h2>@ViewBag.HeadlineSkill</h2>
            <div class="d-flex justify-content-lg-start">
                @foreach (var skill in Model.Skills)
                {
                    <div class="mb-2 content-item">
                        <p class="mb-0">Skill: @skill.ASkill</p>
                        <p class="mb-0">Description of skill: @(skill.Description ?? "")</p>
                        <p class="mb-0">Skill since: @(skill.Date?.ToShortDateString() ?? "Unspecified")</p>
                    </div>
                }
            </div>

        </div>
        <div class="mb-4">
            <h2>@ViewBag.HeadlineCertificates</h2>
            <h5>@ViewBag.HeadlineCertificates</h5>
            <div class="d-flex justify-content-lg-start">
                @foreach (var certificate in Model.Certificates)
                {
                    <div class="mb-2 content-item">
                        <p class="mb-0">Certificate: @certificate.CertName</p>
                    </div>
                }
            </div>

        </div>

        <div class="mb-4" ">
            <h2>@ViewBag.HeadlinePersonalCharacteristics</h2>
            <h5>@ViewBag.HeadlinePersonalCharacteristicsSmall</h5>
            <div class="d-flex justify-content-lg-start">
                @foreach (var personalCharacteristics in Model.PersonalCharacteristics)
                {
                    <div class="mb-2 content-item">
                        <p class="mb-0">@personalCharacteristics.CharacteristicName</p>
                    </div>
                }
            </div>

        </div>

        <div class="mb-4">
            <h2>@ViewBag.HeadlineInterest</h2>
            <h5>@ViewBag.HeadlineInterestSmall</h5>
            <div class="d-flex justify-content-lg-start">
                @foreach (var interest in Model.Interests)
                {
                    <div class="mb-2 content-item">
                        <p class="mb-0">@interest.InterestName</p>
                    </div>
                }
            </div>
        </div>

        <div class="mb-4">
            <h2>@ViewBag.HeadlineProjects</h2>
            <h5>@ViewBag.HeadlineProjectsSmall</h5>
            <div class="d-flex justify-content-lg-start">
                @foreach (var project in Model.UsersProjects)
                {
                    <div class="mb-0 content-item">
                        <p class="mb-0">Title: @project.Title</p>
                        <p class="mb-0">Description: @(project.Description ?? "Not described")</p>
                        <p class="mb-0">Date: @project.StartDate.ToShortDateString() <b>-</b> @(project.Enddate?.ToShortDateString() ?? "Ongoing")</p>
                    </div>
                }
            </div>
        </div>
    </div>
</div>